import { Injectable } from '@angular/core';
import { Employee, EmployeeStatus, EmployeeStatusDescription, EmployeeStatusName, EmployeeGroupName, EmployeeGroupDescription, EmployeeGroup } from '../models/employee-model.models';
import { Subscription, timer } from 'rxjs';
import { MessageService } from 'primeng/api';

@Injectable({ providedIn: 'root' })

export class EmployeeServices {
    constructor(private messageService: MessageService) { }

    public listStatus: EmployeeStatus[] = [
        {
            name: EmployeeStatusName.Active,
            description: EmployeeStatusDescription.Active
        }
        ,
        {
            name: EmployeeStatusName.Inactive,
            description: EmployeeStatusDescription.Inactive
        }
    ]

    public listGroup: EmployeeGroup[] = [
        {
            name: EmployeeGroupName.DEVELOPER,
            description: EmployeeGroupDescription.DEVELOPER
        },
        {
            name: EmployeeGroupName.HR,
            description: EmployeeGroupDescription.HR
        },
        {
            name: EmployeeGroupName.SALE,
            description: EmployeeGroupDescription.SALE,
        },
        {
            name: EmployeeGroupName.MARKETING,
            description: EmployeeGroupDescription.MARKETING
        },
        {
            name: EmployeeGroupName.ADMIN,
            description: EmployeeGroupDescription.ADMIN
        },
        {
            name: EmployeeGroupName.ACCOUNTANT,
            description: EmployeeGroupDescription.ACCOUNTANT
        },
        {
            name: EmployeeGroupName.STAFF,
            description: EmployeeGroupDescription.STAFF
        },
        {
            name: EmployeeGroupName.PROJECT_MANAGER,
            description: EmployeeGroupDescription.PROJECT_MANAGER
        },
        {
            name: EmployeeGroupName.MANAGER,
            description: EmployeeGroupDescription.MANAGER
        },
        {
            name: EmployeeGroupName.DIRECTOR,
            description: EmployeeGroupDescription.DIRECTOR
        }
    ]

    private employees: Employee[] = [
        {
            id: 1,
            username: 'rizwangustama',
            firstName: 'Rizwan',
            lastName: 'Gustama',
            email: 'rizonegustama@gmail.com',
            birthDate: new Date(1999, 9, 8),
            basicSalary: 1000,
            status: EmployeeStatusDescription.Active,
            group: 'DEVELOPER',
            description: 'Description1',
            password: 'admin',
        },
        {
            id: 2,
            username: 'johnsmith',
            firstName: 'John',
            lastName: 'Smith',
            email: 'john.smith@example.com',
            birthDate: new Date(1990, 7, 22),
            basicSalary: 2000,
            status: EmployeeStatusDescription.Inactive,
            group: 'SALE',
            description: 'Description2',
            password: 'Password2',
        },
        {
            id: 3,
            username: 'janedoe',
            firstName: 'Jane',
            lastName: 'Doe',
            email: 'jane.doe@example.com',
            birthDate: new Date(1985, 10, 10),
            basicSalary: 3000,
            status: EmployeeStatusDescription.Active,
            group: 'DEVELOPER',
            description: 'Description3',
            password: 'Password3',
        },
        {
            id: 4,
            username: 'michaeljohnson',
            firstName: 'Michael',
            lastName: 'Johnson',
            email: 'michael.johnson@example.com',
            birthDate: new Date(1992, 4, 5),
            basicSalary: 4000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description4',
            password: 'Password4',
        },
        {
            id: 5,
            username: 'emilydavis',
            firstName: 'Emily',
            lastName: 'Davis',
            email: 'emily.davis@example.com',
            birthDate: new Date(1980, 2, 20),
            basicSalary: 5000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description5',
            password: 'Password5',
        },
        {
            id: 6,
            username: 'williamwilson',
            firstName: 'William',
            lastName: 'Wilson',
            email: 'william.wilson@example.com',
            birthDate: new Date(1975, 8, 15),
            basicSalary: 6000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description6',
            password: 'Password6',
        },
        {
            id: 7,
            username: 'olivertaylor',
            firstName: 'Oliver',
            lastName: 'Taylor',
            email: 'oliver.taylor@example.com',
            birthDate: new Date(1995, 6, 18),
            basicSalary: 7000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description7',
            password: 'Password7',
        },
        {
            id: 8,
            username: 'sophiamartin',
            firstName: 'Sophia',
            lastName: 'Martin',
            email: 'sophia.martin@example.com',
            birthDate: new Date(1988, 11, 30),
            basicSalary: 8000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description8',
            password: 'Password8',
        },
        {
            id: 9,
            username: 'jamesanderson',
            firstName: 'James',
            lastName: 'Anderson',
            email: 'james.anderson@example.com',
            birthDate: new Date(1991, 1, 12),
            basicSalary: 9000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description9',
            password: 'Password9',
        },
        {
            id: 10,
            username: 'amandathomas',
            firstName: 'Amanda',
            lastName: 'Thomas',
            email: 'amanda.thomas@example.com',
            birthDate: new Date(1983, 3, 25),
            basicSalary: 10000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description10',
            password: 'Password10',
        },
        {
            id: 11,
            username: 'davidmoore',
            firstName: 'David',
            lastName: 'Moore',
            email: 'david.moore@example.com',
            birthDate: new Date(1970, 5, 15),
            basicSalary: 11000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description11',
            password: 'Password11',
        },
        {
            id: 12,
            username: 'chrislee',
            firstName: 'Chris',
            lastName: 'Lee',
            email: 'chris.lee@example.com',
            birthDate: new Date(1986, 9, 27),
            basicSalary: 12000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description12',
            password: 'Password12',
        },
        {
            id: 13,
            username: 'jenniferwhite',
            firstName: 'Jennifer',
            lastName: 'White',
            email: 'jennifer.white@example.com',
            birthDate: new Date(1979, 7, 10),
            basicSalary: 13000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description13',
            password: 'Password13',
        },
        {
            id: 14,
            username: 'robertbrown',
            firstName: 'Robert',
            lastName: 'Brown',
            email: 'robert.brown@example.com',
            birthDate: new Date(1990, 4, 23),
            basicSalary: 14000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description14',
            password: 'Password14',
        },
        {
            id: 15,
            username: 'karenwalker',
            firstName: 'Karen',
            lastName: 'Walker',
            email: 'karen.walker@example.com',
            birthDate: new Date(1981, 2, 19),
            basicSalary: 15000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description15',
            password: 'Password15',
        },
        {
            id: 16,
            username: 'joshuahall',
            firstName: 'Joshua',
            lastName: 'Hall',
            email: 'joshua.hall@example.com',
            birthDate: new Date(1993, 3, 17),
            basicSalary: 16000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description16',
            password: 'Password16',
        },
        {
            id: 17,
            username: 'jessicaallen',
            firstName: 'Jessica',
            lastName: 'Allen',
            email: 'jessica.allen@example.com',
            birthDate: new Date(1982, 8, 24),
            basicSalary: 17000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description17',
            password: 'Password17',
        },
        {
            id: 18,
            username: 'danielscott',
            firstName: 'Daniel',
            lastName: 'Scott',
            email: 'daniel.scott@example.com',
            birthDate: new Date(1985, 5, 5),
            basicSalary: 18000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description18',
            password: 'Password18',
        },
        {
            id: 19,
            username: 'ashleyking',
            firstName: 'Ashley',
            lastName: 'King',
            email: 'ashley.king@example.com',
            birthDate: new Date(1996, 7, 29),
            basicSalary: 19000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description19',
            password: 'Password19',
        },
        {
            id: 20,
            username: 'matthewwright',
            firstName: 'Matthew',
            lastName: 'Wright',
            email: 'matthew.wright@example.com',
            birthDate: new Date(1978, 6, 6),
            basicSalary: 20000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description20',
            password: 'Password20',
        },
        {
            id: 22,
            username: 'gregoryrodriguez',
            firstName: 'Gregory',
            lastName: 'Rodriguez',
            email: 'gregory.rodriguez@example.com',
            birthDate: new Date(1987, 11, 12),
            basicSalary: 22000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description22',
            password: 'Password22',
        },
        {
            id: 23,
            username: 'melissamitchell',
            firstName: 'Melissa',
            lastName: 'Mitchell',
            email: 'melissa.mitchell@example.com',
            birthDate: new Date(1984, 4, 27),
            basicSalary: 23000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description23',
            password: 'Password23',
        },
        {
            id: 24,
            username: 'charleslopez',
            firstName: 'Charles',
            lastName: 'Lopez',
            email: 'charles.lopez@example.com',
            birthDate: new Date(1991, 8, 8),
            basicSalary: 24000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description24',
            password: 'Password24',
        },
        {
            id: 25,
            username: 'victoriaedwards',
            firstName: 'Victoria',
            lastName: 'Edwards',
            email: 'victoria.edwards@example.com',
            birthDate: new Date(1983, 2, 14),
            basicSalary: 25000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description25',
            password: 'Password25',
        },
        {
            id: 26,
            username: 'kevinmartin',
            firstName: 'Kevin',
            lastName: 'Martin',
            email: 'kevin.martin@example.com',
            birthDate: new Date(1980, 10, 30),
            basicSalary: 26000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description26',
            password: 'Password26',
        },
        {
            id: 27,
            username: 'amandahernandez',
            firstName: 'Amanda',
            lastName: 'Hernandez',
            email: 'amanda.hernandez@example.com',
            birthDate: new Date(1994, 6, 9),
            basicSalary: 27000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description27',
            password: 'Password27',
        },
        {
            id: 28,
            username: 'richardyoung',
            firstName: 'Richard',
            lastName: 'Young',
            email: 'richard.young@example.com',
            birthDate: new Date(1986, 3, 18),
            basicSalary: 28000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description28',
            password: 'Password28',
        },
        {
            id: 29,
            username: 'jessicawalker',
            firstName: 'Jessica',
            lastName: 'Walker',
            email: 'jessica.walker@example.com',
            birthDate: new Date(1993, 9, 5),
            basicSalary: 29000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description29',
            password: 'Password29',
        },
        {
            id: 30,
            username: 'jonathansanchez',
            firstName: 'Jonathan',
            lastName: 'Sanchez',
            email: 'jonathan.sanchez@example.com',
            birthDate: new Date(1989, 1, 28),
            basicSalary: 30000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description30',
            password: 'Password30',
        },
        {
            id: 31,
            username: 'lisawright',
            firstName: 'Lisa',
            lastName: 'Wright',
            email: 'lisa.wright@example.com',
            birthDate: new Date(1981, 7, 14),
            basicSalary: 31000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description31',
            password: 'Password31',
        },
        {
            id: 32,
            username: 'brianroberts',
            firstName: 'Brian',
            lastName: 'Roberts',
            email: 'brian.roberts@example.com',
            birthDate: new Date(1984, 11, 3),
            basicSalary: 32000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description32',
            password: 'Password32',
        },
        {
            id: 33,
            username: 'monicagarcia',
            firstName: 'Monica',
            lastName: 'Garcia',
            email: 'monica.garcia@example.com',
            birthDate: new Date(1982, 5, 19),
            basicSalary: 33000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description33',
            password: 'Password33',
        },
        {
            id: 34,
            username: 'douglashall',
            firstName: 'Douglas',
            lastName: 'Hall',
            email: 'douglas.hall@example.com',
            birthDate: new Date(1978, 8, 22),
            basicSalary: 34000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description34',
            password: 'Password34',
        },
        {
            id: 35,
            username: 'lauramiller',
            firstName: 'Laura',
            lastName: 'Miller',
            email: 'laura.miller@example.com',
            birthDate: new Date(1990, 3, 11),
            basicSalary: 35000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description35',
            password: 'Password35',
        },
        {
            id: 36,
            username: 'erichernandez',
            firstName: 'Eric',
            lastName: 'Hernandez',
            email: 'eric.hernandez@example.com',
            birthDate: new Date(1976, 6, 6),
            basicSalary: 36000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description36',
            password: 'Password36',
        },
        {
            id: 37,
            username: 'ashleymartinez',
            firstName: 'Ashley',
            lastName: 'Martinez',
            email: 'ashley.martinez@example.com',
            birthDate: new Date(1987, 10, 5),
            basicSalary: 37000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description37',
            password: 'Password37',
        },
        {
            id: 38,
            username: 'adamsullivan',
            firstName: 'Adam',
            lastName: 'Sullivan',
            email: 'adam.sullivan@example.com',
            birthDate: new Date(1983, 2, 28),
            basicSalary: 38000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description38',
            password: 'Password38',
        },
        {
            id: 39,
            username: 'christophergreen',
            firstName: 'Christopher',
            lastName: 'Green',
            email: 'christopher.green@example.com',
            birthDate: new Date(1991, 4, 17),
            basicSalary: 39000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description39',
            password: 'Password39',
        },
        {
            id: 40,
            username: 'jessicalopez',
            firstName: 'Jessica',
            lastName: 'Lopez',
            email: 'jessica.lopez@example.com',
            birthDate: new Date(1985, 8, 30),
            basicSalary: 40000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description40',
            password: 'Password40',
        },
        {
            id: 41,
            username: 'michaelallen',
            firstName: 'Michael',
            lastName: 'Allen',
            email: 'michael.allen@example.com',
            birthDate: new Date(1992, 0, 15),
            basicSalary: 41000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description41',
            password: 'Password41',
        },
        {
            id: 42,
            username: 'sarahnichols',
            firstName: 'Sarah',
            lastName: 'Nichols',
            email: 'sarah.nichols@example.com',
            birthDate: new Date(1985, 3, 22),
            basicSalary: 42000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description42',
            password: 'Password42',
        },
        {
            id: 43,
            username: 'williamward',
            firstName: 'William',
            lastName: 'Ward',
            email: 'william.ward@example.com',
            birthDate: new Date(1983, 7, 11),
            basicSalary: 43000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description43',
            password: 'Password43',
        },
        {
            id: 44,
            username: 'katherinelee',
            firstName: 'Katherine',
            lastName: 'Lee',
            email: 'katherine.lee@example.com',
            birthDate: new Date(1988, 10, 9),
            basicSalary: 44000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description44',
            password: 'Password44',
        },
        {
            id: 45,
            username: 'josephjackson',
            firstName: 'Joseph',
            lastName: 'Jackson',
            email: 'joseph.jackson@example.com',
            birthDate: new Date(1990, 1, 20),
            basicSalary: 45000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description45',
            password: 'Password45',
        },
        {
            id: 46,
            username: 'nicoleshaw',
            firstName: 'Nicole',
            lastName: 'Shaw',
            email: 'nicole.shaw@example.com',
            birthDate: new Date(1986, 4, 18),
            basicSalary: 46000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description46',
            password: 'Password46',
        },
        {
            id: 47,
            username: 'davidreyes',
            firstName: 'David',
            lastName: 'Reyes',
            email: 'david.reyes@example.com',
            birthDate: new Date(1987, 2, 27),
            basicSalary: 47000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description47',
            password: 'Password47',
        },
        {
            id: 48,
            username: 'angelaharris',
            firstName: 'Angela',
            lastName: 'Harris',
            email: 'angela.harris@example.com',
            birthDate: new Date(1991, 5, 25),
            basicSalary: 48000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description48',
            password: 'Password48',
        },
        {
            id: 49,
            username: 'ryanrobinson',
            firstName: 'Ryan',
            lastName: 'Robinson',
            email: 'ryan.robinson@example.com',
            birthDate: new Date(1984, 9, 14),
            basicSalary: 49000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description49',
            password: 'Password49',
        },
        {
            id: 50,
            username: 'meganwhite',
            firstName: 'Megan',
            lastName: 'White',
            email: 'megan.white@example.com',
            birthDate: new Date(1989, 11, 5),
            basicSalary: 50000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description50',
            password: 'Password50',
        },
        {
            id: 51,
            username: 'danielyoung',
            firstName: 'Daniel',
            lastName: 'Young',
            email: 'daniel.young@example.com',
            birthDate: new Date(1983, 6, 17),
            basicSalary: 51000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description51',
            password: 'Password51',
        },
        {
            id: 52,
            username: 'lauracampbell',
            firstName: 'Laura',
            lastName: 'Campbell',
            email: 'laura.campbell@example.com',
            birthDate: new Date(1981, 1, 7),
            basicSalary: 52000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description52',
            password: 'Password52',
        },
        {
            id: 53,
            username: 'matthewperez',
            firstName: 'Matthew',
            lastName: 'Perez',
            email: 'matthew.perez@example.com',
            birthDate: new Date(1992, 4, 23),
            basicSalary: 53000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description53',
            password: 'Password53',
        },
        {
            id: 54,
            username: 'emilyhill',
            firstName: 'Emily',
            lastName: 'Hill',
            email: 'emily.hill@example.com',
            birthDate: new Date(1984, 2, 16),
            basicSalary: 54000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description54',
            password: 'Password54',
        },
        {
            id: 55,
            username: 'brianclark',
            firstName: 'Brian',
            lastName: 'Clark',
            email: 'brian.clark@example.com',
            birthDate: new Date(1987, 9, 12),
            basicSalary: 55000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description55',
            password: 'Password55',
        },
        {
            id: 56,
            username: 'heathergarcia',
            firstName: 'Heather',
            lastName: 'Garcia',
            email: 'heather.garcia@example.com',
            birthDate: new Date(1990, 7, 6),
            basicSalary: 56000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description56',
            password: 'Password56',
        },
        {
            id: 57,
            username: 'jamesmartinez',
            firstName: 'James',
            lastName: 'Martinez',
            email: 'james.martinez@example.com',
            birthDate: new Date(1985, 6, 20),
            basicSalary: 57000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description57',
            password: 'Password57',
        },
        {
            id: 58,
            username: 'amberthompson',
            firstName: 'Amber',
            lastName: 'Thompson',
            email: 'amber.thompson@example.com',
            birthDate: new Date(1988, 8, 30),
            basicSalary: 58000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description58',
            password: 'Password58',
        },
        {
            id: 59,
            username: 'patrickmiller',
            firstName: 'Patrick',
            lastName: 'Miller',
            email: 'patrick.miller@example.com',
            birthDate: new Date(1982, 11, 22),
            basicSalary: 59000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description59',
            password: 'Password59',
        },
        {
            id: 60,
            username: 'rachelmartin',
            firstName: 'Rachel',
            lastName: 'Martin',
            email: 'rachel.martin@example.com',
            birthDate: new Date(1991, 2, 18),
            basicSalary: 60000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description60',
            password: 'Password60',
        },
        {
            id: 61,
            username: 'alexjohnson',
            firstName: 'Alex',
            lastName: 'Johnson',
            email: 'alex.johnson@example.com',
            birthDate: new Date(1987, 1, 15),
            basicSalary: 61000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description61',
            password: 'Password61',
        },
        {
            id: 62,
            username: 'emilybrown',
            firstName: 'Emily',
            lastName: 'Brown',
            email: 'emily.brown@example.com',
            birthDate: new Date(1990, 3, 25),
            basicSalary: 62000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description62',
            password: 'Password62',
        },
        {
            id: 63,
            username: 'davidwilson',
            firstName: 'David',
            lastName: 'Wilson',
            email: 'david.wilson@example.com',
            birthDate: new Date(1985, 5, 5),
            basicSalary: 63000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description63',
            password: 'Password63',
        },
        {
            id: 64,
            username: 'saradavis',
            firstName: 'Sara',
            lastName: 'Davis',
            email: 'sara.davis@example.com',
            birthDate: new Date(1992, 7, 12),
            basicSalary: 64000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description64',
            password: 'Password64',
        },
        {
            id: 65,
            username: 'michaelmiller',
            firstName: 'Michael',
            lastName: 'Miller',
            email: 'michael.miller@example.com',
            birthDate: new Date(1988, 9, 28),
            basicSalary: 65000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description65',
            password: 'Password65',
        },
        {
            id: 66,
            username: 'laurawilliams',
            firstName: 'Laura',
            lastName: 'Williams',
            email: 'laura.williams@example.com',
            birthDate: new Date(1989, 11, 14),
            basicSalary: 66000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description66',
            password: 'Password66',
        },
        {
            id: 67,
            username: 'jamesmartin',
            firstName: 'James',
            lastName: 'Martin',
            email: 'james.martin@example.com',
            birthDate: new Date(1983, 2, 22),
            basicSalary: 67000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description67',
            password: 'Password67',
        },
        {
            id: 68,
            username: 'carolthomas',
            firstName: 'Carol',
            lastName: 'Thomas',
            email: 'carol.thomas@example.com',
            birthDate: new Date(1985, 4, 3),
            basicSalary: 68000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description68',
            password: 'Password68',
        },
        {
            id: 69,
            username: 'chrisroberts',
            firstName: 'Chris',
            lastName: 'Roberts',
            email: 'chris.roberts@example.com',
            birthDate: new Date(1991, 6, 30),
            basicSalary: 69000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description69',
            password: 'Password69',
        },
        {
            id: 70,
            username: 'elizabethtaylor',
            firstName: 'Elizabeth',
            lastName: 'Taylor',
            email: 'elizabeth.taylor@example.com',
            birthDate: new Date(1987, 8, 19),
            basicSalary: 70000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description70',
            password: 'Password70',
        },
        {
            id: 71,
            username: 'paulmoore',
            firstName: 'Paul',
            lastName: 'Moore',
            email: 'paul.moore@example.com',
            birthDate: new Date(1990, 10, 7),
            basicSalary: 71000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description71',
            password: 'Password71',
        },
        {
            id: 72,
            username: 'jennifergarcia',
            firstName: 'Jennifer',
            lastName: 'Garcia',
            email: 'jennifer.garcia@example.com',
            birthDate: new Date(1984, 0, 17),
            basicSalary: 72000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description72',
            password: 'Password72',
        },
        {
            id: 73,
            username: 'markmartinez',
            firstName: 'Mark',
            lastName: 'Martinez',
            email: 'mark.martinez@example.com',
            birthDate: new Date(1986, 3, 21),
            basicSalary: 73000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description73',
            password: 'Password73',
        },
        {
            id: 74,
            username: 'nancylee',
            firstName: 'Nancy',
            lastName: 'Lee',
            email: 'nancy.lee@example.com',
            birthDate: new Date(1992, 2, 14),
            basicSalary: 74000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description74',
            password: 'Password74',
        },
        {
            id: 75,
            username: 'robertharris',
            firstName: 'Robert',
            lastName: 'Harris',
            email: 'robert.harris@example.com',
            birthDate: new Date(1981, 4, 26),
            basicSalary: 75000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description75',
            password: 'Password75',
        },
        {
            id: 76,
            username: 'lisajones',
            firstName: 'Lisa',
            lastName: 'Jones',
            email: 'lisa.jones@example.com',
            birthDate: new Date(1988, 6, 8),
            basicSalary: 76000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description76',
            password: 'Password76',
        },
        {
            id: 77,
            username: 'stephencampbell',
            firstName: 'Stephen',
            lastName: 'Campbell',
            email: 'stephen.campbell@example.com',
            birthDate: new Date(1991, 8, 24),
            basicSalary: 77000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description77',
            password: 'Password77',
        },
        {
            id: 78,
            username: 'sandrabaker',
            firstName: 'Sandra',
            lastName: 'Baker',
            email: 'sandra.baker@example.com',
            birthDate: new Date(1983, 10, 29),
            basicSalary: 78000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description78',
            password: 'Password78',
        },
        {
            id: 79,
            username: 'brendaturner',
            firstName: 'Brenda',
            lastName: 'Turner',
            email: 'brenda.turner@example.com',
            birthDate: new Date(1985, 11, 11),
            basicSalary: 79000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description79',
            password: 'Password79',
        },
        {
            id: 80,
            username: 'kennethclark',
            firstName: 'Kenneth',
            lastName: 'Clark',
            email: 'kenneth.clark@example.com',
            birthDate: new Date(1993, 0, 3),
            basicSalary: 80000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description80',
            password: 'Password80',
        },
        {
            id: 81,
            username: 'jacobjones',
            firstName: 'Jacob',
            lastName: 'Jones',
            email: 'jacob.jones@example.com',
            birthDate: new Date(1991, 1, 10),
            basicSalary: 81000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description81',
            password: 'Password81',
        },
        {
            id: 82,
            username: 'kimberlyyoung',
            firstName: 'Kimberly',
            lastName: 'Young',
            email: 'kimberly.young@example.com',
            birthDate: new Date(1989, 3, 20),
            basicSalary: 82000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description82',
            password: 'Password82',
        },
        {
            id: 83,
            username: 'richardking',
            firstName: 'Richard',
            lastName: 'King',
            email: 'richard.king@example.com',
            birthDate: new Date(1985, 5, 18),
            basicSalary: 83000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description83',
            password: 'Password83',
        },
        {
            id: 84,
            username: 'madisonhill',
            firstName: 'Madison',
            lastName: 'Hill',
            email: 'madison.hill@example.com',
            birthDate: new Date(1987, 7, 24),
            basicSalary: 84000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description84',
            password: 'Password84',
        },
        {
            id: 85,
            username: 'anthonymoore',
            firstName: 'Anthony',
            lastName: 'Moore',
            email: 'anthony.moore@example.com',
            birthDate: new Date(1986, 9, 13),
            basicSalary: 85000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description85',
            password: 'Password85',
        },
        {
            id: 86,
            username: 'katherinelee',
            firstName: 'Katherine',
            lastName: 'Lee',
            email: 'katherine.lee@example.com',
            birthDate: new Date(1983, 11, 5),
            basicSalary: 86000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description86',
            password: 'Password86',
        },
        {
            id: 87,
            username: 'danieljackson',
            firstName: 'Daniel',
            lastName: 'Jackson',
            email: 'daniel.jackson@example.com',
            birthDate: new Date(1990, 2, 15),
            basicSalary: 87000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description87',
            password: 'Password87',
        },
        {
            id: 88,
            username: 'angelacampbell',
            firstName: 'Angela',
            lastName: 'Campbell',
            email: 'angela.campbell@example.com',
            birthDate: new Date(1992, 4, 28),
            basicSalary: 88000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description88',
            password: 'Password88',
        },
        {
            id: 89,
            username: 'kevinmartin',
            firstName: 'Kevin',
            lastName: 'Martin',
            email: 'kevin.martin@example.com',
            birthDate: new Date(1984, 6, 17),
            basicSalary: 89000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description89',
            password: 'Password89',
        },
        {
            id: 90,
            username: 'amberbrown',
            firstName: 'Amber',
            lastName: 'Brown',
            email: 'amber.brown@example.com',
            birthDate: new Date(1991, 8, 25),
            basicSalary: 90000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description90',
            password: 'Password90',
        },
        {
            id: 91,
            username: 'ethangreen',
            firstName: 'Ethan',
            lastName: 'Green',
            email: 'ethan.green@example.com',
            birthDate: new Date(1988, 10, 8),
            basicSalary: 91000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description91',
            password: 'Password91',
        },
        {
            id: 92,
            username: 'samanthawhite',
            firstName: 'Samantha',
            lastName: 'White',
            email: 'samantha.white@example.com',
            birthDate: new Date(1985, 0, 12),
            basicSalary: 92000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description92',
            password: 'Password92',
        },
        {
            id: 93,
            username: 'justinmartinez',
            firstName: 'Justin',
            lastName: 'Martinez',
            email: 'justin.martinez@example.com',
            birthDate: new Date(1993, 3, 9),
            basicSalary: 93000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description93',
            password: 'Password93',
        },
        {
            id: 94,
            username: 'ashleyhernandez',
            firstName: 'Ashley',
            lastName: 'Hernandez',
            email: 'ashley.hernandez@example.com',
            birthDate: new Date(1990, 5, 18),
            basicSalary: 94000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description94',
            password: 'Password94',
        },
        {
            id: 95,
            username: 'brandonwilson',
            firstName: 'Brandon',
            lastName: 'Wilson',
            email: 'brandon.wilson@example.com',
            birthDate: new Date(1987, 7, 21),
            basicSalary: 95000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description95',
            password: 'Password95',
        },
        {
            id: 96,
            username: 'sarahthomas',
            firstName: 'Sarah',
            lastName: 'Thomas',
            email: 'sarah.thomas@example.com',
            birthDate: new Date(1992, 9, 2),
            basicSalary: 96000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description96',
            password: 'Password96',
        },
        {
            id: 97,
            username: 'benjaminwright',
            firstName: 'Benjamin',
            lastName: 'Wright',
            email: 'benjamin.wright@example.com',
            birthDate: new Date(1986, 11, 13),
            basicSalary: 97000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description97',
            password: 'Password97',
        },
        {
            id: 98,
            username: 'rachelclark',
            firstName: 'Rachel',
            lastName: 'Clark',
            email: 'rachel.clark@example.com',
            birthDate: new Date(1983, 2, 15),
            basicSalary: 98000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description98',
            password: 'Password98',
        },
        {
            id: 99,
            username: 'joshuathompson',
            firstName: 'Joshua',
            lastName: 'Thompson',
            email: 'joshua.thompson@example.com',
            birthDate: new Date(1989, 4, 28),
            basicSalary: 99000,
            status: EmployeeStatusDescription.Active,
            group: 'ADMIN',
            description: 'Description99',
            password: 'Password99',
        },
        {
            id: 100,
            username: 'briancampbell',
            firstName: 'Brian',
            lastName: 'Campbell',
            email: 'brian.campbell@example.com',
            birthDate: new Date(1991, 6, 19),
            basicSalary: 100000,
            status: EmployeeStatusDescription.Inactive,
            group: 'ADMIN',
            description: 'Description100',
            password: 'Password100',
        }
    ]

    getListStatus(): EmployeeStatus[] {
        return this.listStatus;
    }


    getListEmployeeGroup(): EmployeeGroup[] {
        return this.listGroup;
    }

    getEmployees(): Employee[] {
        return this.employees;
    }

    getEmployeeById(id: number): Employee | undefined {
        return this.employees.find(employee => employee.id === id);
    }

    updateEmployee(employee: Employee): void {
        const index = this.employees.findIndex(e => e.id === employee.id);
        if (index !== -1) {
            this.employees[index] = employee;
            console.log('Employee updated successfully');
        }
    }

    addEmployee(employee: Employee): void {
        this.employees.unshift(employee);
        console.log('Employee added successfully');
    }
    
}